### PR TITLE
#326 Made journey section font size bigger

### PR DESCRIPTION
**Pull request by Eldi47**
The font size for the journey section appeared too small for devices 1200px and lower so I changed the `font-size:` to be in `vw` so that the text size is consistent in all width confirgurations.

### CODE REVIEW

**Review by asynchroza — CHANGES_REQUESTED** [review]
Text is too big now, it should be somewhere in between the current change and the previous state

**Comment by SuelaCark** [comment]
@Eldi47 update your branch with master (do this in your LOCAL branch and push the changes, not the shortcut of github). If you need guidance, read the [wiki (click here).](https://github.com/AUBGTheHUB/spa-website-2022/wiki/Pull-Requests-and-Updating-branches-with-master)

**Review by SuelaCark — CHANGES_REQUESTED** [review]
Text for mobile devices with width from 600-1200px is too big. Try using font-size with rem/em instead of vw

**Review by SuelaCark — CHANGES_REQUESTED** [review]
Now the font is too big for mobile. Try to work with something similar to what you had worked 1 commit before, but use media queries to make font-adjustments.

image

**Comment by SuelaCark** [comment]
@Aleks1908 @asynchroza @nikolayninov Please review the changes made and approve if you think that the font-sizes are better adjusted now. If there needs to be any additional changes, please ping @Eldi47

**Review by Aleks1908 — APPROVED** [review]

**Pull request merged**
