### PR TITLE
#291 remove margin-bottom on awards section

### PR DESCRIPTION
**Pull request by annakukova**
#291 Removed margin-bottom on awards-section-container and renamed the container in the CSS to something shorter

### CODE REVIEW

**Review by SuelaCark — COMMENTED** [review]
LGTM, but idk if you are supposed to have the new services/mailer_service files within this branch

**Review by SuelaCark — APPROVED** [review]
LGTM. @asynchroza @nikolayninov @Aleks1908 review and merge

**Review by SuelaCark — APPROVED** [review]

**Review by Aleks1908 — APPROVED** [review]
LGTM

**Comment by SuelaCark** [comment]
@asynchroza @nikolayninov please review and merge this PR since I am unable to do so (because I have committed code and approved it aswell).

**Comment by asynchroza** [comment]
In my opinion the awards section should be scaling proportionally. Desktop version almost the same size as the one on mobile devices. I'm leaving my approve but you should probably discuss that @SuelaCark @annakukova @savinadd

**Review by asynchroza — APPROVED** [review]

**Comment by SuelaCark** [comment]
@Eldi47 @MiroGorski @Pessy1 Please work on the responsiveness of the awards section. Make the pictures of the awards bigger for desktop (only desktop).

**Comment by Eldi47** [comment]
@SuelaCark reopen this PR

**Pull request closed without merging**
