### PR TITLE
#177 video section

### PR DESCRIPTION
**Pull request by SuelaCark**
Created video section and implemented the HackAUBG 4.0 video

### CODE REVIEW

**Comment by asynchroza** [comment]
I'm testing the workflow

**Comment by asynchroza** [comment]
Testing github actions frontend workflow

**Comment by asynchroza** [comment]
Same here. Resolve the animation PR first.

**Review by asynchroza — CHANGES_REQUESTED** [review]
Resolve issues in Hack Animation PR, merge it in master then resolve issues here.

**Comment by asynchroza** [comment]
Let's first merge the animation PR then clean up everything which shouldn't be here such as the judge section.

**Review by nikolayninov — APPROVED** [review]

**Review by nikolayninov — APPROVED** [review]

**Comment by asynchroza** [comment]
There are still leftover files which don't match master.

**Review by nikolayninov — APPROVED** [review]

**Review by nikolayninov — APPROVED** [review]

**Review by asynchroza — APPROVED** [review]

**Pull request merged**
