### PR TITLE
#183 faq section

### PR DESCRIPTION
**Pull request by SuelaCark**
#183 Changed font colors to fit the design, added text and change font-family to 'Roboto'

### CODE REVIEW

**Review by r-mishev — APPROVED** [review]
LGTM 👍🏽

**Review by asynchroza — CHANGES_REQUESTED** [review]
LeFtOvEr GiF fIlE

**Comment by SuelaCark** [comment]
> LeFtOvEr GiF fIlE

I saw it yesterday. That's why I didn't MeEeerGeee after the approval.

**Comment by SuelaCark** [comment]
@asynchroza @r-mishev @Aleks1908 @AUBGTheHUB/nosyncdev

**Review by asynchroza — APPROVED** [review]

**Pull request merged**
