### PR TITLE
#376 Remove required tag from TeamName field in TeamMember struct 

### LINKED ISSUE #376: Make TeamName field in TeamMember struct not required

### PR DESCRIPTION
**Pull request by IvanObreshkov**
Fix #376

### CODE REVIEW

**Review by asynchroza — APPROVED** [review]
@IvanObreshkov did you verify if everything is working as expected? If all three cases are handled as expected, feel free to merge this

**Comment by IvanObreshkov** [comment]
> @IvanObreshkov did you verify if everything is working as expected? If all three cases are handled as expected, feel free to merge this

The normal case when the hasTeam is false works as expected (the person is added to the noTeamCollection)
Aleks said in the front-end if the person says he has a team and fills nothing it it si going to notify them that this filed is required. And also when the person clicks No on hasTeam TeamName is going to become inactive.

**Comment by asynchroza** [comment]
> > @IvanObreshkov did you verify if everything is working as expected? If all three cases are handled as expected, feel free to merge this
> 
> @asynchroza The normal case when the hasTeam is false and teamName is "" works as expected (the person is added to the noTeamCollection) Aleks said in the front end if the person says he has a team and fills nothing in teamName it is going to notify them that this filed is required. And also when the person clicks No on hasTeam TeamName is going to become inactive.

It's preferable that you test by not actually passing the key (since this will be the way how the frontend will pass the object to the api), but "" is still considered  a null value so I don't expect that there would be any issue with that. 

I kind of get lost in what you're trying to explain. We handled the issue on the frontend where the field is visible even when `hasTeam` is false. This PR will fix the backend part of the problem. 

CC: @Aleks1908

**Comment by asynchroza** [comment]
> > > > @IvanObreshkov did you verify if everything is working as expected? If all three cases are handled as expected, feel free to merge this
> > > 
> > > 
> > > @asynchroza The normal case when the hasTeam is false and teamName is "" works as expected (the person is added to the noTeamCollection) Aleks said in the front end if the person says he has a team and fills nothing in teamName it is going to notify them that this filed is required. And also when the person clicks No on hasTeam TeamName is going to become inactive.
> > 
> > 
> > It's preferable that you test by not actually passing the key (since this will be the way how the frontend will pass the object to the api), but "" is still considered a null value so I don't expect that there would be any issue with that.
> > I kind of get lost in what you're trying to explain. We handled the issue on the frontend where the field is visible even when `hasTeam` is false. This PR will fix the backend part of the problem.
> > CC: @Aleks1908
> 
> I tested it without providing the teamname key, and the document appears in the DB with the kye as "teamname": "", which I think is the way it should be.

yep, that's not an issue

**Comment by IvanObreshkov** [comment]
> > > > > @IvanObreshkov did you verify if everything is working as expected? If all three cases are handled as expected, feel free to merge this
> > > > 
> > > > 
> > > > @asynchroza The normal case when the hasTeam is false and teamName is "" works as expected (the person is added to the noTeamCollection) Aleks said in the front end if the person says he has a team and fills nothing in teamName it is going to notify them that this filed is required. And also when the person clicks No on hasTeam TeamName is going to become inactive.
> > > 
> > > 
> > > It's preferable that you test by not actually passing the key (since this will be the way how the frontend will pass the object to the api), but "" is still considered a null value so I don't expect that there would be any issue with that.
> > > I kind of get lost in what you're trying to explain. We handled the issue on the frontend where the field is visible even when `hasTeam` is false. This PR will fix the backend part of the problem.
> > > CC: @Aleks1908
> > 
> > 
> > I tested it without providing the teamname key, and the document appears in the DB with the kye as "teamname": "", which I think is the way it should be.
> 
> yep, that's not an issue

Gud, merging

**Pull request merged**
