### PR TITLE
#221 connect all appropriate anchors

### PR DESCRIPTION
**Pull request by DemonHashira**

### CODE REVIEW

**Review by nikolayninov — APPROVED** [review]

**Comment by asynchroza** [comment]
@Aleks1908 are the changes in the 404page's css expected? Can you verify if everything is working there as expected?

**Comment by Aleks1908** [comment]
> @Aleks1908 are the changes in the 404page's css expected? Can you verify if everything is working there as expected?

I think what Victor did is we worked on his issue on the 404 page and i think he must have created the branch for this issue not from master but from his other issue and thats why the 404 page is being modified

**Comment by asynchroza** [comment]
> > @Aleks1908 are the changes in the 404page's css expected? Can you verify if everything is working there as expected?
> 
> I think what Victor did is we worked on his issue on the 404 page and i think he must have created the branch for this issue not from master but from his other issue and thats why the 404 page is being modified. But I can confirm that all the links work

@DemonHashira resolve this, the only changes which should be applied from this PR should be only the ones the issue is addressing -> hence linking all of the anchors

**Review by SuelaCark — CHANGES_REQUESTED** [review]
Please remove the changes made for the 404-page (refer to the above comments @Aleks1908 and @asynchroza made). Also, work on having a smoother moving transition because for instance, if you are at the top and decide to click on faq, the sliding effects its a little too fast. 

Side note: The grading criteria section file structure is being worked on in another PR. Hence, we might need to connect the grading criteria section again later after merging the PR.

**Review by SuelaCark — APPROVED** [review]
LGTM. To what I can see through the code and comparing between branches, @DemonHashira has removed all changes made for the 404page from this PR.

**Pull request merged**
