### PR TITLE
#232 changed favicon

### PR DESCRIPTION
**Pull request by SuelaCark**
#232  Changed favicon to the neon green HUB logo

### CODE REVIEW

**Comment by SuelaCark** [comment]
@annakukova Please now work on designing the main favicon (same as HackAUBG favicon just with color neon blue) and implement the logic so that the main favicon will be shown in all webpages, but HackAUBG will have only the neon green favicon.

**Comment by asynchroza** [comment]
This favicon is being applied globally

**Comment by asynchroza** [comment]
@SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).

What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one.

**Comment by nikolayninov** [comment]
> @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> 
> What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)

She used Helmet which gets the job done in an elegant way :D

**Review by asynchroza — CHANGES_REQUESTED** [review]
requesting changes so that I dismiss @nikolayninov's approval

**Comment by asynchroza** [comment]
> > @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> > What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)
> 
> She used Helmet which gets the job done in an elegant way :D

What do you mean? I don't see anything.

**Comment by nikolayninov** [comment]
> > > @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> > > What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)
> > 
> > 
> > She used Helmet which gets the job done in an elegant way :D
> 
> What do you mean? I don't see anything.

She pushed the commit 10 mins ago but it doesn't show on the PR. It's there on the branch though

**Comment by asynchroza** [comment]
> > > > @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> > > > What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)
> > > 
> > > 
> > > She used Helmet which gets the job done in an elegant way :D
> > 
> > 
> > What do you mean? I don't see anything.
> 
> She pushed the commit 10 mins ago but it doesn't show on the PR. It's there on the branch though

I think you're mistaken. Here are the changes Anna has applied - https://github.com/AUBGTheHUB/spa-website-2022/compare/%23232-Add-hub-logo-favicon

**Comment by nikolayninov** [comment]
Nvm, she pushed to the wrong branch. Apparently, @SuelaCark made a branch called #232-favicon and @annakukova used the other one #232-Add-hub-logo-favicon

**Comment by SuelaCark** [comment]
@annakukova I was checking your branch and saw that it was out-of-date with master, so I tried to merge master into your branch ([#232-Add-hub-logo-favicon](https://github.com/AUBGTheHUB/spa-website-2022/compare/%23232-Add-hub-logo-favicon)). However, you have numerous merge conflicts and since the changes in your branch were only a few, I decided to just add the changes in THIS branch #232-favicon. I added everything from your branch including react-helmet, but removed unnecessary old favicons. Hence, now please work on _this branch only_ (#232-favicon) and resolve the above comments made by @asynchroza (meaning to remove react-helmet and implement a global function instead, because the react-helmet is taking too long to load). 

Additionally, I saw that the green favicon dimensions were 256x256px while the blue favicon had 32x32px. While this doesnt play much role, you can notice the quality difference between the favicons. 

> @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> 
> What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)

**Comment by asynchroza** [comment]
> @annakukova I was checking your branch and saw that it was out-of-date with master, so I tried to merge master into your branch ([#232-Add-hub-logo-favicon](https://github.com/AUBGTheHUB/spa-website-2022/compare/%23232-Add-hub-logo-favicon)). However, you have numerous merge conflicts and since the changes in your branch were only a few, I decided to just add the changes in THIS branch #232-favicon. I added everything from your branch including react-helmet, but removed unnecessary old favicons. Hence, now please work on _this branch only_ (#232-favicon) and resolve the above comments made by @asynchroza (meaning to remove react-helmet and implement a global function instead, because the react-helmet is taking too long to load).
> 
> Additionally, I saw that the green favicon dimensions were 256x256px while the blue favicon had 32x32px. While this doesnt play much role, you can notice the quality difference between the favicons.
> 
> > @SuelaCark @annakukova here are a couple of solutions on how to change the favicon using javascript - [click me](https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically).
> > What you need to do is to name the default blue favicon - `favicon` (this is how it's referenced in index.html), and come up with a global function which is triggered by an eventListener listening for url change. This function should check if the url has `HackAUBG` in it and if it does, set the favicon to the green one, if it doesn't - set the blue one. If something is not clear open a thread [here](https://discord.com/channels/1035257919031226449/1075513463473983570)

* 256x256 is too high of a resolution for a favicon. It should be either 16x16/32x32 - [Read about favicons and different devices here](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs#:~:text=Set%20the%20width%20and%20height,bit%20alpha%2C%20no%20palette%20settings.&text=Scale%20the%20image%20down%20to,and%20check%20the%20icon%20visibility.). Does the normal favicon get rendered when viewed from a phone or we should specify that as well?
[TEST]: on apple devices the favicon cant be seen

* I see why you merged her changes but this PR should be rebuilt from the ground up. Why? Because she has deleted the reference to `manifest.json` and has some redundant files such as the one found here -> https://github.com/AUBGTheHUB/spa-website-2022/pull/299/commits/461f17350d11d7c1af2cad454bb404d518c740c4. Index html has been changed which is bad. What she needs to do is update the manifest accordingly and just add the corresponding default icons.

**Pull request closed without merging**
